### ISSUE TITLE
Implement overlay open file

### ISSUE THREAD

**Issue by gerardroche** [gerardroche/sublime-polyfill#2]
- [x] in split `ctrl+s`
- [x] in vsplit `ctrl+v`
- [x] in tab `ctrl+t`

**Comment by mreq** [comment]
@gerardroche Would you mind adding [Origami](https://github.com/SublimeText/Origami) as a dependency for this feature? I'd implement this happily if that was an option (using Origami anyways).

**Comment by gerardroche** [comment]
I'm open to it if it can be implemented in a non intrusive way or as a temporary solution. 

By non-intrusive I mean for example, polyfill should work without Origami installed and should only fail silently when Origami is not installed. 

Ideally, I'd like see a window api plugin that provides just the window commands with no side effects e.g. doesn't override key bindings. This way both Origami aswell as other plugins like [Vintageous Origami](https://github.com/rodcloutier/Vintageous-Origami) could use those commands without the side effects. 

I've played around with this idea in a develop branch of [Vintageous](https://github.com/gerardroche/Vintageous/tree/fa3881e11b28af15690bf2509771b113835e2321). See the [SublimeWindowApi](https://github.com/gerardroche/Vintageous/blob/fa3881e11b28af15690bf2509771b113835e2321/sublime_ext.py). I've implemented a few of a features of Origami, mostly because [Vintageous Origami](https://github.com/rodcloutier/Vintageous-Origami) doesn't work with the newer versions of Vintageous and the Vim window commands are a little different than Origami. Vim rearranges windows rather than moving them.

**Comment by gerardroche** [comment]
It was a good idea. I don't know why I didn't do this in the first place. I remember looking at Origami and can't remember why I didn't use it.

Anyways, thanks for bringing this to my attention.

I wasn't able to get the open file in split, vsplit, and tab from the tree view #1. Not sure yet if it's possible.

**Comment by mreq** [comment]
good job :+1:
